---
apiVersion: v2
name: czertainly
description: A demo Helm Chart for CZERTAINLY deployment
version: 1.0.0
dependencies:
  - name: czertainly
    version: 2.16.2
    repository: "oci://harbor.3key.company/czertainly-helm"